name: Post News to Telegram

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  post-news:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the script
    - name: Run Python Script
      env:
        API_KEY: ${{ secrets.API_KEY }}         # Gemini API Key from GitHub Secrets
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}     # Telegram Bot Token from GitHub Secrets
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}   # Telegram Channel ID from GitHub Secrets
      run: |
        python your_script_name.py
